application: oexchange-digg
version: 1
runtime: python
api_version: 1

handlers:

- url: /.well-known
  static_dir: well-known
  mime_type: application/xrd+xml
   
- url: /oexchange
  static_dir: oexchange
  mime_type: application/xrd+xml

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /
  static_files: index.html
  upload: index.html